#!/bin/bash

echo Identificando arquitetura do processador
if [[ $(uname -p) == 'arm' ]]; then
  echo Processador Silicon
  echo Baixando Wireshark para ARM64
  WiresharkURL="https://2.na.dl.wireshark.org/osx/Wireshark%20Latest%20Arm%2064.dmg"
else
  echo Processador Intel
  echo Baixando Wireshark para x64
  WiresharkURL="https://2.na.dl.wireshark.org/osx/Wireshark%20Latest%20Intel%2064.dmg"
fi


echo Identificando versão atual do Wireshark
echo Wireshark Latest localizado
echo Iniciando download do Wireshark Latest
/usr/bin/curl --location --silent "$WiresharkURL" -o "/private/tmp/$(echo $WiresharkURL | sed 's/\// /g' | awk '{print $NF}' | sed 's/%20/_/g')"

echo Montando disco
hdiutil attach "/private/tmp/$(echo $WiresharkURL | sed 's/\// /g' | awk '{print $NF}' | sed 's/%20/_/g')"

echo Copiando Wireshark.app para /Applications
cp -Rf /Volumes/Wireshark*/Wireshark.app /Applications

installer -pkg /Volumes/Wireshark*/Install\ ChmodBPF.pkg -target /

installer -pkg /Volumes/Wireshark*/Add\ Wireshark\ to\ the\ system\ path.pkg -target /

echo Desmontando disco
hdiutil detach /Volumes/Wireshark*

if [[ -e /Applications/Wireshark.app ]];
then
  echo Wireshark instalado com sucesso
  exit 0
else
  echo Falha ao instalar Wireshark
  exit 1
fi
